name: "TypeScript Build"
description: "Build TypeScript code and optionally push the compiled code to a different branch"
author: "Alex Kovacs"
inputs:
  branch:
    description: "The name of the branch the action should push the compiled code"
    required: false
    default: "dist"
  githubToken:
    description: "Your GitHub secret token"
    required: true
runs:
  using: "node18"
  main: index.js
